#!/bin/bash
# RedHat Server
# Tomcat installation
cd /opt 
sudo hostname tomcat3
sudo yum install java-1.8.0-openjdk-devel -y
sudo yum install git wget -y
sudo wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
sudo tar -xvf apache-tomcat-9.0.64.tar.gz
sudo rm -rf apache-tomcat-9.0.64.tar.gz
sudo mv apache-tomcat-9.0.64 tomcat9
sudo chmod 777 -R /opt/tomcat9
sudo sh /opt/tomcat9/bin/startup.sh
